# Generated by Django 3.2.13 on 2022-11-21 02:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backdrop_image',
            field=models.ImageField(blank=True, default='', upload_to=accounts.models.backdrop_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to=accounts.models.profile_image_path),
        ),
    ]
