# Generated by Django 3.2.13 on 2022-11-21 04:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backdrop_image',
            field=models.ImageField(blank=True, default='/backdrop/default.jpg', upload_to=accounts.models.backdrop_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile/default.png', upload_to=accounts.models.profile_image_path),
        ),
    ]
