# Generated by Django 3.2.13 on 2022-11-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221122_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='animation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='comedy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='documentary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='drama',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fantasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='horror',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='music',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mystery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='romance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='science_fiction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='thriller',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tv_movie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='war',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='western',
            field=models.IntegerField(default=0),
        ),
    ]
