# Generated by Django 3.2.13 on 2022-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
