# Generated by Django 3.2.13 on 2022-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_nowmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('audi_cnt', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
    ]
