# Generated by Django 3.2.13 on 2022-11-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_boxoffice_nowmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='field_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
