name: BE Deploy

on:
  push:
    branches:
      - release/BE

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd ~/boogie-project
            git pull
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
